### ISSUE TITLE
Buttons to copy text to clipboard on Export page don't work

### ISSUE THREAD

**Issue by aracat** [mintyfresh/EquineEventRedux#5]
Firefox 120.0.1 x64 on Windows

Error in console: Uncaught TypeError: navigator.clipboard is undefined

**Comment by mintyfresh** [comment]
I've added a fallback mechanism to copy if navigator is not available.
It appears that it's unsupported in insecure contexts, although localhost seems to have an exception to that restriction, at least in Chrome.
