### ISSUE TITLE
Inconsistent sorting between Players page and Export page where players have the same tiebreakers

### ISSUE THREAD

**Issue by aracat** [mintyfresh/EquineEventRedux#6]
Unsure exactly why this happens, but got into a situation where two players have the same score and first tiebreaker, but are presented in different orders on the Players page vs the Export page. The second tiebreaker would not appear to matter in this circumstance because the two players didn't encounter each other. The ordering discrepancy might be due to one of the pages honoring the final tiebreaker of Random and the other not doing so.

**Comment by mintyfresh** [comment]
The problems looks to have been that the players export table was re-sorted with a slightly different tie-breaker, yes.
I've correct this issue to always tiebreak on ID, which is a randomly generated UUID. Basically a coin-flip.
